name: practice-1

on:
  push:
    branches: main

  workflow_dispatch:

  issues:
    types: opened, closed

jobs:
  build:
    runs-on:  ubuntu-latest
    
    steps:
      - uses: actions/checkout@4.2.2

      - name: print Hello World
        run: echo "Hello World"

      - name: upload
        uses: actions/upload-artifact@4.6.0
        with:
          name: build=artifact
          path: ${{github.workspace}}

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: download
        uses: actions/download-artifact@4.1.8
        with:
          name: build=artifact
          path: ${{github.workspace}}
